export default {
  // To make the scales of the palnets and distances consistent, i'm going to use muliplies on
  // top of the earth's size for everything else. that makes it one adjustable parameter for them all.
  SUN_SCALE_MULTIPLIER: 10.9,
  SUN_DISTANCE_MULTIPLIER: 0, // It's the center

  MERCURY_SCALE_MULTIPLIER: 0.38,
  MERCURY_DISTANCE_MULTIPLIER: 61.8,
  MERCURY_ORBITAL_PERIOD: 88, 
  MERCURY_ORBITAL_ECCENTRICITY: 0.2056,

  VENUS_SCALE_MULTIPLIER: 0.95,
  VENUS_DISTANCE_MULTIPLIER: 115.3,
  VENUS_ORBITAL_PERIOD: 224.7,
  VENUS_ORBITAL_ECCENTRICITY: 0.0068,

  EARTH_SCALE_MULTIPLIER: 1,
  EARTH_DISTANCE_MULTIPLIER: 149.6,
  EARTH_ORBITAL_PERIOD: 365.25,
  EARTH_ORBITAL_ECCENTRICITY: 0.0167,

  MOON_SCALE_MULTIPLIER: 0.27,
  MOON_DISTANCE_MULTIPLIER: 0.26, // Moon is ~384,400 km from Earth
  MOON_ORBITAL_PERIOD: 27.3, 
  MOON_ORBITAL_ECCENTRICITY: 0.0549,

  MARS_SCALE_MULTIPLIER: 0.53,
  MARS_DISTANCE_MULTIPLIER: 227.9,
  MARS_ORBITAL_PERIOD: 686.97,
  MARS_ORBITAL_ECCENTRICITY: 0.0934,

  JUPITER_SCALE_MULTIPLIER: 11.21,
  JUPITER_DISTANCE_MULTIPLIER: 778.5,
  JUPITER_ORBITAL_PERIOD: 4332.59,
  JUPITER_ORBITAL_ECCENTRICITY: 0.0489,

  SATURN_SCALE_MULTIPLIER: 9.45,
  SATURN_DISTANCE_MULTIPLIER: 1433.5,
  SATURN_ORBITAL_PERIOD: 10759.22, 
  SATURN_ORBITAL_ECCENTRICITY: 0.0565,

  URANUS_SCALE_MULTIPLIER: 4.01,
  URANUS_DISTANCE_MULTIPLIER: 2872.5,
  URANUS_ORBITAL_PERIOD: 30688.5, 
  URANUS_ORBITAL_ECCENTRICITY: 0.0463,

  NEPTUNE_SCALE_MULTIPLIER: 3.88,
  NEPTUNE_DISTANCE_MULTIPLIER: 4495.1,
  NEPTUNE_ORBITAL_PERIOD: 60182, 
  NEPTUNE_ORBITAL_ECCENTRICITY: 0.0086,

  sunColor: "#fc9601",
  earthAtmosphereDayColor: "#00aaff",
  earthAtmosphereTwilightColor: "#ff6600",
};
